/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/Global_DEFINES.h"
#include "Headers/BasicTypes.h"
#include "Headers/CoreUObject_UFunction.h"
#include "Headers/BP_MissionTaskMove_PARAMS.h"
#include "Headers/BP_MissionTaskMove_ABP_MissionTaskMove_C.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::BP_MissionTaskMove
{
    // --------------------------------------------------
    // # Structs functions
    // --------------------------------------------------
    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/Blueprints/Mission/BP_MissionTaskMove.BP_MissionTaskMove_C.TaskActorStateChanged
     *         Flags  -> (Event, Protected, BlueprintEvent)
     * Parameters:
     *         M1::EM1EventActorState                             InState                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         void                                               ReturnValue
     */
    void ABP_MissionTaskMove_C::TaskActorStateChanged(M1::EM1EventActorState InState)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/Mission/BP_MissionTaskMove.BP_MissionTaskMove_C.TaskActorStateChanged");
        
        ABP_MissionTaskMove_C_TaskActorStateChanged_Params params {};
        params.InState = InState;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/Blueprints/Mission/BP_MissionTaskMove.BP_MissionTaskMove_C.ExecuteUbergraph_BP_MissionTaskMove
     *         Flags  -> (Final)
     * Parameters:
     *         int32_t                                            EntryPoint                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         void                                               ReturnValue
     */
    void ABP_MissionTaskMove_C::ExecuteUbergraph_BP_MissionTaskMove(int32_t EntryPoint)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/Mission/BP_MissionTaskMove.BP_MissionTaskMove_C.ExecuteUbergraph_BP_MissionTaskMove");
        
        ABP_MissionTaskMove_C_ExecuteUbergraph_BP_MissionTaskMove_Params params {};
        params.EntryPoint = EntryPoint;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
