/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/Global_DEFINES.h"
#include "Headers/BasicTypes.h"
#include "Headers/CoreUObject_UFunction.h"
#include "Headers/BP_Vulgus_AnchorStone_TopCore_PARAMS.h"
#include "Headers/BP_Vulgus_AnchorStone_TopCore_ABP_Vulgus_AnchorStone_TopCore_C.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::BP_Vulgus_AnchorStone_TopCore
{
    // --------------------------------------------------
    // # Structs functions
    // --------------------------------------------------
    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/BG/BG_AnimBP/ForestDead/Vulgus_AnchorStone_TopCore/BP_Vulgus_AnchorStone_TopCore.BP_Vulgus_AnchorStone_TopCore_C.ReceiveBeginPlay
     *         Flags  -> (Event, Protected, BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void ABP_Vulgus_AnchorStone_TopCore_C::ReceiveBeginPlay()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/BG/BG_AnimBP/ForestDead/Vulgus_AnchorStone_TopCore/BP_Vulgus_AnchorStone_TopCore.BP_Vulgus_AnchorStone_TopCore_C.ReceiveBeginPlay");
        
        ABP_Vulgus_AnchorStone_TopCore_C_ReceiveBeginPlay_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/BG/BG_AnimBP/ForestDead/Vulgus_AnchorStone_TopCore/BP_Vulgus_AnchorStone_TopCore.BP_Vulgus_AnchorStone_TopCore_C.ExecuteUbergraph_BP_Vulgus_AnchorStone_TopCore
     *         Flags  -> (Final)
     * Parameters:
     *         int32_t                                            EntryPoint                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         void                                               ReturnValue
     */
    void ABP_Vulgus_AnchorStone_TopCore_C::ExecuteUbergraph_BP_Vulgus_AnchorStone_TopCore(int32_t EntryPoint)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/BG/BG_AnimBP/ForestDead/Vulgus_AnchorStone_TopCore/BP_Vulgus_AnchorStone_TopCore.BP_Vulgus_AnchorStone_TopCore_C.ExecuteUbergraph_BP_Vulgus_AnchorStone_TopCore");
        
        ABP_Vulgus_AnchorStone_TopCore_C_ExecuteUbergraph_BP_Vulgus_AnchorStone_TopCore_Params params {};
        params.EntryPoint = EntryPoint;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
