/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/Global_DEFINES.h"
#include "Headers/BasicTypes.h"
#include "Headers/CoreUObject_UFunction.h"
#include "Headers/BPL_Runes_PARAMS.h"
#include "Headers/BPL_Runes_UBPL_Runes_C.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::BPL_Runes
{
    // --------------------------------------------------
    // # Structs functions
    // --------------------------------------------------
    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.ShowChildrenOfParent
     *         Flags  -> (Static, Public, BlueprintCallable, BlueprintEvent)
     * Parameters:
     *         UMG::UPanelWidget*                                 InParent                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
     *         int32_t                                            InCountToShow                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         CoreUObject::UObject*                              __WorldContext                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
     *         void                                               ReturnValue
     */
    void UBPL_Runes_C::STATIC_ShowChildrenOfParent(UMG::UPanelWidget* InParent, int32_t InCountToShow, CoreUObject::UObject* __WorldContext)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.ShowChildrenOfParent");
        
        UBPL_Runes_C_ShowChildrenOfParent_Params params {};
        params.InParent = InParent;
        params.InCountToShow = InCountToShow;
        params.__WorldContext = __WorldContext;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.SetEnchantLevelIcon
     *         Flags  -> (Public, BlueprintCallable, BlueprintEvent)
     * Parameters:
     *         UI_RuneEnchant_Icon::UUI_RuneEnchant_Icon_C*       InEnchantLevelIcon                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
     *         int32_t                                            InLevel                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         CoreUObject::UObject*                              __WorldContext                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
     *         void                                               ReturnValue
     */
    void UBPL_Runes_C::SetEnchantLevelIcon(UI_RuneEnchant_Icon::UUI_RuneEnchant_Icon_C* InEnchantLevelIcon, int32_t InLevel, CoreUObject::UObject* __WorldContext)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.SetEnchantLevelIcon");
        
        UBPL_Runes_C_SetEnchantLevelIcon_Params params {};
        params.InEnchantLevelIcon = InEnchantLevelIcon;
        params.InLevel = InLevel;
        params.__WorldContext = __WorldContext;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.Get Tooltip Text by Rune Class
     *         Flags  -> (Static, Public, HasOutParms, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
     * Parameters:
     *         M1Data::EM1RuneClassType                           InRuneClassType                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         M1::EM1UITextType                                  InType                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         CoreUObject::UObject*                              __WorldContext                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
     *         BasicTypes::FText                                  ReturnValue                                                (Parm, OutParm, ReturnParm)
     */
    BasicTypes::FText UBPL_Runes_C::STATIC_GetTooltipTextbyRuneClass(M1Data::EM1RuneClassType InRuneClassType, M1::EM1UITextType InType, CoreUObject::UObject* __WorldContext)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.Get Tooltip Text by Rune Class");
        
        UBPL_Runes_C_GetTooltipTextbyRuneClass_Params params {};
        params.InRuneClassType = InRuneClassType;
        params.InType = InType;
        params.__WorldContext = __WorldContext;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
        
        return params.ReturnValue;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.Get Text By Supported Types By Rune Class
     *         Flags  -> (Static, Public, HasOutParms, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
     * Parameters:
     *         M1Data::EM1RuneClassType                           InRuneClassType                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         M1::EM1UITextType                                  InType                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         CoreUObject::UObject*                              __WorldContext                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
     *         BasicTypes::FText                                  ReturnValue                                                (Parm, OutParm, ReturnParm)
     */
    BasicTypes::FText UBPL_Runes_C::STATIC_GetTextBySupportedTypesByRuneClass(M1Data::EM1RuneClassType InRuneClassType, M1::EM1UITextType InType, CoreUObject::UObject* __WorldContext)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.Get Text By Supported Types By Rune Class");
        
        UBPL_Runes_C_GetTextBySupportedTypesByRuneClass_Params params {};
        params.InRuneClassType = InRuneClassType;
        params.InType = InType;
        params.__WorldContext = __WorldContext;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
        
        return params.ReturnValue;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.GetTextBySocketType
     *         Flags  -> (Static, Public, HasOutParms, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
     * Parameters:
     *         M1Data::EM1RuneSocketType                          InSocketColor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         CoreUObject::UObject*                              __WorldContext                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
     *         BasicTypes::FText                                  ReturnValue                                                (Parm, OutParm, ReturnParm)
     */
    BasicTypes::FText UBPL_Runes_C::STATIC_GetTextBySocketType(M1Data::EM1RuneSocketType InSocketColor, CoreUObject::UObject* __WorldContext)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.GetTextBySocketType");
        
        UBPL_Runes_C_GetTextBySocketType_Params params {};
        params.InSocketColor = InSocketColor;
        params.__WorldContext = __WorldContext;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
        
        return params.ReturnValue;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.Get Text by Rune Class Type Capacity
     *         Flags  -> (Static, Public, HasOutParms, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
     * Parameters:
     *         M1Data::EM1RuneClassType                           InRuneClassType                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         CoreUObject::UObject*                              __WorldContext                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
     *         BasicTypes::FText                                  ReturnValue                                                (Parm, OutParm, ReturnParm)
     */
    BasicTypes::FText UBPL_Runes_C::STATIC_GetTextbyRuneClassTypeCapacity(M1Data::EM1RuneClassType InRuneClassType, CoreUObject::UObject* __WorldContext)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.Get Text by Rune Class Type Capacity");
        
        UBPL_Runes_C_GetTextbyRuneClassTypeCapacity_Params params {};
        params.InRuneClassType = InRuneClassType;
        params.__WorldContext = __WorldContext;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
        
        return params.ReturnValue;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.GetTextByRuneClassType
     *         Flags  -> (Static, Public, HasOutParms, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
     * Parameters:
     *         M1Data::EM1RuneClassType                           InClassType                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         CoreUObject::UObject*                              __WorldContext                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
     *         BasicTypes::FText                                  NewParam                                                   (Parm, OutParm)
     *         void                                               ReturnValue
     */
    void UBPL_Runes_C::STATIC_GetTextByRuneClassType(M1Data::EM1RuneClassType InClassType, CoreUObject::UObject* __WorldContext, BasicTypes::FText* NewParam)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.GetTextByRuneClassType");
        
        UBPL_Runes_C_GetTextByRuneClassType_Params params {};
        params.InClassType = InClassType;
        params.__WorldContext = __WorldContext;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
        
        if (NewParam != nullptr)
            *NewParam = params.NewParam;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.GetTextByItemClassType
     *         Flags  -> (Static, Public, HasOutParms, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
     * Parameters:
     *         M1Data::EM1EquipItemClassType                      ItemClassType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         CoreUObject::UObject*                              __WorldContext                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
     *         BasicTypes::FText                                  Text                                                       (Parm, OutParm)
     *         void                                               ReturnValue
     */
    void UBPL_Runes_C::STATIC_GetTextByItemClassType(M1Data::EM1EquipItemClassType ItemClassType, CoreUObject::UObject* __WorldContext, BasicTypes::FText* Text)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.GetTextByItemClassType");
        
        UBPL_Runes_C_GetTextByItemClassType_Params params {};
        params.ItemClassType = ItemClassType;
        params.__WorldContext = __WorldContext;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
        
        if (Text != nullptr)
            *Text = params.Text;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.Get Tab Text By Supported Types By Rune Class
     *         Flags  -> (Static, Public, HasOutParms, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
     * Parameters:
     *         M1Data::EM1RuneClassType                           InRuneClassType                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         M1::EM1UITextType                                  InType                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         CoreUObject::UObject*                              __WorldContext                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
     *         BasicTypes::FText                                  ReturnValue                                                (Parm, OutParm, ReturnParm)
     */
    BasicTypes::FText UBPL_Runes_C::STATIC_GetTabTextBySupportedTypesByRuneClass(M1Data::EM1RuneClassType InRuneClassType, M1::EM1UITextType InType, CoreUObject::UObject* __WorldContext)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.Get Tab Text By Supported Types By Rune Class");
        
        UBPL_Runes_C_GetTabTextBySupportedTypesByRuneClass_Params params {};
        params.InRuneClassType = InRuneClassType;
        params.InType = InType;
        params.__WorldContext = __WorldContext;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
        
        return params.ReturnValue;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.Get Rune Socket Type Mini Image
     *         Flags  -> (Static, Public, HasOutParms, BlueprintCallable, BlueprintEvent, BlueprintPure)
     * Parameters:
     *         M1Data::EM1RuneSocketType                          InRuneSocketType                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         CoreUObject::UObject*                              __WorldContext                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
     *         Engine::UTexture2D*                                ReturnValue                                                (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
     */
    Engine::UTexture2D* UBPL_Runes_C::STATIC_GetRuneSocketTypeMiniImage(M1Data::EM1RuneSocketType InRuneSocketType, CoreUObject::UObject* __WorldContext)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.Get Rune Socket Type Mini Image");
        
        UBPL_Runes_C_GetRuneSocketTypeMiniImage_Params params {};
        params.InRuneSocketType = InRuneSocketType;
        params.__WorldContext = __WorldContext;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
        
        return params.ReturnValue;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.Get Rune Socket Image
     *         Flags  -> (Static, Public, HasOutParms, BlueprintCallable, BlueprintEvent, BlueprintPure)
     * Parameters:
     *         M1Data::EM1RuneSocketType                          InType                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         CoreUObject::UObject*                              __WorldContext                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
     *         Engine::UTexture2D*                                ReturnValue                                                (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
     */
    Engine::UTexture2D* UBPL_Runes_C::STATIC_GetRuneSocketImage(M1Data::EM1RuneSocketType InType, CoreUObject::UObject* __WorldContext)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.Get Rune Socket Image");
        
        UBPL_Runes_C_GetRuneSocketImage_Params params {};
        params.InType = InType;
        params.__WorldContext = __WorldContext;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
        
        return params.ReturnValue;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.Get Rune Class Type Mini Image
     *         Flags  -> (Static, Public, HasOutParms, BlueprintCallable, BlueprintEvent, BlueprintPure)
     * Parameters:
     *         M1Data::EM1RuneClassType                           InRuneClassType                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         CoreUObject::UObject*                              __WorldContext                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
     *         Engine::UTexture2D*                                ReturnValue                                                (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
     */
    Engine::UTexture2D* UBPL_Runes_C::STATIC_GetRuneClassTypeMiniImage(M1Data::EM1RuneClassType InRuneClassType, CoreUObject::UObject* __WorldContext)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.Get Rune Class Type Mini Image");
        
        UBPL_Runes_C_GetRuneClassTypeMiniImage_Params params {};
        params.InRuneClassType = InRuneClassType;
        params.__WorldContext = __WorldContext;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
        
        return params.ReturnValue;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.GetRuneClassTypeBackImage
     *         Flags  -> (Static, Public, HasOutParms, BlueprintCallable, BlueprintEvent, BlueprintPure)
     * Parameters:
     *         M1Data::EM1RuneClassType                           InRuneClassType                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         CoreUObject::UObject*                              __WorldContext                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
     *         Engine::UTexture2D*                                ReturnValue                                                (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
     */
    Engine::UTexture2D* UBPL_Runes_C::STATIC_GetRuneClassTypeBackImage(M1Data::EM1RuneClassType InRuneClassType, CoreUObject::UObject* __WorldContext)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.GetRuneClassTypeBackImage");
        
        UBPL_Runes_C_GetRuneClassTypeBackImage_Params params {};
        params.InRuneClassType = InRuneClassType;
        params.__WorldContext = __WorldContext;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
        
        return params.ReturnValue;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.Get Rune Board Slot Soket Icon in Empty Bg
     *         Flags  -> (Static, Public, HasOutParms, BlueprintCallable, BlueprintEvent, BlueprintPure)
     * Parameters:
     *         M1Data::EM1RuneSocketType                          InType                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         CoreUObject::UObject*                              __WorldContext                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
     *         Engine::UTexture2D*                                ReturnValue                                                (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
     */
    Engine::UTexture2D* UBPL_Runes_C::STATIC_GetRuneBoardSlotSoketIconinEmptyBg(M1Data::EM1RuneSocketType InType, CoreUObject::UObject* __WorldContext)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.Get Rune Board Slot Soket Icon in Empty Bg");
        
        UBPL_Runes_C_GetRuneBoardSlotSoketIconinEmptyBg_Params params {};
        params.InType = InType;
        params.__WorldContext = __WorldContext;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
        
        return params.ReturnValue;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.Get Rune Class Color Type
     *         Flags  -> (Static, Public, BlueprintCallable, BlueprintEvent)
     * Parameters:
     *         UMG::UImage*                                       SetImage                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
     *         M1Data::EM1RuneClassType                           InRuneClassType                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         CoreUObject::UObject*                              __WorldContext                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
     *         void                                               ReturnValue
     */
    void UBPL_Runes_C::STATIC_GetRuneClassColorType(UMG::UImage* SetImage, M1Data::EM1RuneClassType InRuneClassType, CoreUObject::UObject* __WorldContext)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.Get Rune Class Color Type");
        
        UBPL_Runes_C_GetRuneClassColorType_Params params {};
        params.SetImage = SetImage;
        params.InRuneClassType = InRuneClassType;
        params.__WorldContext = __WorldContext;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.GetIconImageByItemClassType
     *         Flags  -> (Static, Public, HasOutParms, BlueprintCallable, BlueprintEvent, BlueprintPure)
     * Parameters:
     *         M1Data::EM1EquipItemClassType                      ItemClassType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         CoreUObject::UObject*                              __WorldContext                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
     *         Engine::UTexture2D*                                Image                                                      (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
     *         void                                               ReturnValue
     */
    void UBPL_Runes_C::STATIC_GetIconImageByItemClassType(M1Data::EM1EquipItemClassType ItemClassType, CoreUObject::UObject* __WorldContext, Engine::UTexture2D** Image)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Runes/BPL_Runes.BPL_Runes_C.GetIconImageByItemClassType");
        
        UBPL_Runes_C_GetIconImageByItemClassType_Params params {};
        params.ItemClassType = ItemClassType;
        params.__WorldContext = __WorldContext;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
        
        if (Image != nullptr)
            *Image = params.Image;
    }

}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
