/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/Global_DEFINES.h"
#include "Headers/BasicTypes.h"
#include "Headers/CoreUObject_UFunction.h"
#include "Headers/GLTFExporter_ENUMS.h"
#include "Headers/GLTFExporter_PARAMS.h"
#include "Headers/GLTFExporter_UGLTFMaterialExportOptions.h"
#include "Headers/GLTFExporter_UGLTFExportOptions.h"
#include "Headers/GLTFExporter_UGLTFExporter.h"
#include "Headers/GLTFExporter_UGLTFAnimSequenceExporter.h"
#include "Headers/GLTFExporter_UGLTFLevelExporter.h"
#include "Headers/GLTFExporter_UGLTFLevelSequenceExporter.h"
#include "Headers/GLTFExporter_UGLTFLevelVariantSetsExporter.h"
#include "Headers/GLTFExporter_UGLTFMaterialExporter.h"
#include "Headers/GLTFExporter_UGLTFSkeletalMeshExporter.h"
#include "Headers/GLTFExporter_UGLTFStaticMeshExporter.h"
#include "Headers/GLTFExporter_UGLTFProxyOptions.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::GLTFExporter
{
    // --------------------------------------------------
    // # Structs functions
    // --------------------------------------------------
    /**
     * Function:
     *         RVA    -> 0x01F6DEF0
     *         Name   -> Function /Script/GLTFExporter.GLTFExportOptions.ResetToDefault
     *         Flags  -> (Final, Native, Public, BlueprintCallable)
     * Parameters:
     *         void                                               ReturnValue
     */
    void UGLTFExportOptions::ResetToDefault()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GLTFExporter.GLTFExportOptions.ResetToDefault");
        
        UGLTFExportOptions_ResetToDefault_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x01F7E910
     *         Name   -> Function /Script/GLTFExporter.GLTFExporter.ExportToGLTF
     *         Flags  -> (Final, Native, Static, Public, HasOutParms, BlueprintCallable)
     * Parameters:
     *         CoreUObject::UObject*                              Object                                                     (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
     *         BasicTypes::FString                                FilePath                                                   (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
     *         GLTFExporter::UGLTFExportOptions*                  Options                                                    (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
     *         BasicTypes::TSet<Engine::AActor*>                  SelectedActors                                             (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
     *         GLTFExporter::FGLTFExportMessages                  OutMessages                                                (Parm, OutParm, NativeAccessSpecifierPublic)
     *         bool                                               ReturnValue                                                (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
     */
    bool UGLTFExporter::STATIC_ExportToGLTF(CoreUObject::UObject* Object, const BasicTypes::FString& FilePath, GLTFExporter::UGLTFExportOptions* Options, BasicTypes::TSet<Engine::AActor*> SelectedActors, GLTFExporter::FGLTFExportMessages* OutMessages)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GLTFExporter.GLTFExporter.ExportToGLTF");
        
        UGLTFExporter_ExportToGLTF_Params params {};
        params.Object = Object;
        params.FilePath = FilePath;
        params.Options = Options;
        params.SelectedActors = SelectedActors;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
        
        if (OutMessages != nullptr)
            *OutMessages = params.OutMessages;
        
        return params.ReturnValue;
    }

    /**
     * Function:
     *         RVA    -> 0x01F88AE0
     *         Name   -> Function /Script/GLTFExporter.GLTFProxyOptions.ResetToDefault
     *         Flags  -> (Final, Native, Public, BlueprintCallable)
     * Parameters:
     *         void                                               ReturnValue
     */
    void UGLTFProxyOptions::ResetToDefault()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GLTFExporter.GLTFProxyOptions.ResetToDefault");
        
        UGLTFProxyOptions_ResetToDefault_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
