/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/Global_DEFINES.h"
#include "Headers/BasicTypes.h"
#include "Headers/CoreUObject_UFunction.h"
#include "Headers/MediaCompositing_UMovieSceneMediaPlayerPropertySection.h"
#include "Headers/MediaCompositing_UMovieSceneMediaPlayerPropertyTrack.h"
#include "Headers/MediaCompositing_UMovieSceneMediaSection.h"
#include "Headers/MediaCompositing_UMovieSceneMediaTrack.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::MediaCompositing
{
    // --------------------------------------------------
    // # Structs functions
    // --------------------------------------------------

}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
