/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/Global_DEFINES.h"
#include "Headers/BasicTypes.h"
#include "Headers/CoreUObject_UFunction.h"
#include "Headers/NPC_009_Jeffer_Barricade01A_PARAMS.h"
#include "Headers/NPC_009_Jeffer_Barricade01A_ANPC_009_Jeffer_Barricade01A_C.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::NPC_009_Jeffer_Barricade01A
{
    // --------------------------------------------------
    // # Structs functions
    // --------------------------------------------------
    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/Blueprints/Character/NPC/NPC_009_Jeffer_Barricade01A.NPC_009_Jeffer_Barricade01A_C.ReceiveBeginPlay
     *         Flags  -> (Event, Protected, BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void ANPC_009_Jeffer_Barricade01A_C::ReceiveBeginPlay()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/Character/NPC/NPC_009_Jeffer_Barricade01A.NPC_009_Jeffer_Barricade01A_C.ReceiveBeginPlay");
        
        ANPC_009_Jeffer_Barricade01A_C_ReceiveBeginPlay_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/Blueprints/Character/NPC/NPC_009_Jeffer_Barricade01A.NPC_009_Jeffer_Barricade01A_C.ReceiveActorBeginOverlap
     *         Flags  -> (Event, Public, BlueprintEvent)
     * Parameters:
     *         Engine::AActor*                                    OtherActor                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
     *         void                                               ReturnValue
     */
    void ANPC_009_Jeffer_Barricade01A_C::ReceiveActorBeginOverlap(Engine::AActor* OtherActor)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/Character/NPC/NPC_009_Jeffer_Barricade01A.NPC_009_Jeffer_Barricade01A_C.ReceiveActorBeginOverlap");
        
        ANPC_009_Jeffer_Barricade01A_C_ReceiveActorBeginOverlap_Params params {};
        params.OtherActor = OtherActor;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/Blueprints/Character/NPC/NPC_009_Jeffer_Barricade01A.NPC_009_Jeffer_Barricade01A_C.ReceiveTick
     *         Flags  -> (Event, Public, BlueprintEvent)
     * Parameters:
     *         float                                              DeltaSeconds                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         void                                               ReturnValue
     */
    void ANPC_009_Jeffer_Barricade01A_C::ReceiveTick(float DeltaSeconds)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/Character/NPC/NPC_009_Jeffer_Barricade01A.NPC_009_Jeffer_Barricade01A_C.ReceiveTick");
        
        ANPC_009_Jeffer_Barricade01A_C_ReceiveTick_Params params {};
        params.DeltaSeconds = DeltaSeconds;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/Blueprints/Character/NPC/NPC_009_Jeffer_Barricade01A.NPC_009_Jeffer_Barricade01A_C.ExecuteUbergraph_NPC_009_Jeffer_Barricade01A
     *         Flags  -> (Final)
     * Parameters:
     *         int32_t                                            EntryPoint                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         void                                               ReturnValue
     */
    void ANPC_009_Jeffer_Barricade01A_C::ExecuteUbergraph_NPC_009_Jeffer_Barricade01A(int32_t EntryPoint)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/Character/NPC/NPC_009_Jeffer_Barricade01A.NPC_009_Jeffer_Barricade01A_C.ExecuteUbergraph_NPC_009_Jeffer_Barricade01A");
        
        ANPC_009_Jeffer_Barricade01A_C_ExecuteUbergraph_NPC_009_Jeffer_Barricade01A_Params params {};
        params.EntryPoint = EntryPoint;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
