/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/Global_DEFINES.h"
#include "Headers/BasicTypes.h"
#include "Headers/CoreUObject_UFunction.h"
#include "Headers/UI_Game_ForcedExitTime_PARAMS.h"
#include "Headers/UI_Game_ForcedExitTime_UUI_Game_ForcedExitTime_C.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::UI_Game_ForcedExitTime
{
    // --------------------------------------------------
    // # Structs functions
    // --------------------------------------------------
    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Game/Widgets/UI_Game_ForcedExitTime.UI_Game_ForcedExitTime_C.OnEventWidgetOpen
     *         Flags  -> (Event, Protected, BlueprintEvent)
     * Parameters:
     *         M1::EM1WidgetAnimDirection                         InDirection                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         void                                               ReturnValue
     */
    void UUI_Game_ForcedExitTime_C::OnEventWidgetOpen(M1::EM1WidgetAnimDirection InDirection)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Game/Widgets/UI_Game_ForcedExitTime.UI_Game_ForcedExitTime_C.OnEventWidgetOpen");
        
        UUI_Game_ForcedExitTime_C_OnEventWidgetOpen_Params params {};
        params.InDirection = InDirection;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Game/Widgets/UI_Game_ForcedExitTime.UI_Game_ForcedExitTime_C.ExecuteUbergraph_UI_Game_ForcedExitTime
     *         Flags  -> (Final)
     * Parameters:
     *         int32_t                                            EntryPoint                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         void                                               ReturnValue
     */
    void UUI_Game_ForcedExitTime_C::ExecuteUbergraph_UI_Game_ForcedExitTime(int32_t EntryPoint)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Game/Widgets/UI_Game_ForcedExitTime.UI_Game_ForcedExitTime_C.ExecuteUbergraph_UI_Game_ForcedExitTime");
        
        UUI_Game_ForcedExitTime_C_ExecuteUbergraph_UI_Game_ForcedExitTime_Params params {};
        params.EntryPoint = EntryPoint;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
