/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/Global_DEFINES.h"
#include "Headers/BasicTypes.h"
#include "Headers/CoreUObject_UFunction.h"
#include "Headers/UI_MapBattleZoneUnlockNoti_PARAMS.h"
#include "Headers/UI_MapBattleZoneUnlockNoti_UUI_MapBattleZoneUnlockNoti_C.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::UI_MapBattleZoneUnlockNoti
{
    // --------------------------------------------------
    // # Structs functions
    // --------------------------------------------------
    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Game/Widgets/UI_MapBattleZoneUnlockNoti.UI_MapBattleZoneUnlockNoti_C.SequenceEvent__ENTRYPOINTUI_MapBattleZoneUnlockNoti
     *         Flags  -> (Public, BlueprintCallable, BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void UUI_MapBattleZoneUnlockNoti_C::SequenceEvent__ENTRYPOINTUI_MapBattleZoneUnlockNoti()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Game/Widgets/UI_MapBattleZoneUnlockNoti.UI_MapBattleZoneUnlockNoti_C.SequenceEvent__ENTRYPOINTUI_MapBattleZoneUnlockNoti");
        
        UUI_MapBattleZoneUnlockNoti_C_SequenceEvent__ENTRYPOINTUI_MapBattleZoneUnlockNoti_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Game/Widgets/UI_MapBattleZoneUnlockNoti.UI_MapBattleZoneUnlockNoti_C.BP_widget_playAkEvent
     *         Flags  -> (BlueprintCallable, BlueprintEvent)
     * Parameters:
     *         AkAudio::UAkAudioEvent*                            AkEvent                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
     *         void                                               ReturnValue
     */
    void UUI_MapBattleZoneUnlockNoti_C::BP_widget_playAkEvent(AkAudio::UAkAudioEvent* AkEvent)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Game/Widgets/UI_MapBattleZoneUnlockNoti.UI_MapBattleZoneUnlockNoti_C.BP_widget_playAkEvent");
        
        UUI_MapBattleZoneUnlockNoti_C_BP_widget_playAkEvent_Params params {};
        params.AkEvent = AkEvent;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Game/Widgets/UI_MapBattleZoneUnlockNoti.UI_MapBattleZoneUnlockNoti_C.ExecuteUbergraph_UI_MapBattleZoneUnlockNoti
     *         Flags  -> (Final)
     * Parameters:
     *         int32_t                                            EntryPoint                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         void                                               ReturnValue
     */
    void UUI_MapBattleZoneUnlockNoti_C::ExecuteUbergraph_UI_MapBattleZoneUnlockNoti(int32_t EntryPoint)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Game/Widgets/UI_MapBattleZoneUnlockNoti.UI_MapBattleZoneUnlockNoti_C.ExecuteUbergraph_UI_MapBattleZoneUnlockNoti");
        
        UUI_MapBattleZoneUnlockNoti_C_ExecuteUbergraph_UI_MapBattleZoneUnlockNoti_Params params {};
        params.EntryPoint = EntryPoint;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
