/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/Global_DEFINES.h"
#include "Headers/BasicTypes.h"
#include "Headers/CoreUObject_UFunction.h"
#include "Headers/UI_SkillCustomHUD_BunnyActive4_PARAMS.h"
#include "Headers/UI_SkillCustomHUD_BunnyActive4_UUI_SkillCustomHUD_BunnyActive4_C.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::UI_SkillCustomHUD_BunnyActive4
{
    // --------------------------------------------------
    // # Structs functions
    // --------------------------------------------------
    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Game/Widgets/SkillCustomHUD/UI_SkillCustomHUD_BunnyActive4.UI_SkillCustomHUD_BunnyActive4_C.UpdateBeamLevelGauge
     *         Flags  -> (Public, BlueprintCallable, BlueprintEvent)
     * Parameters:
     *         int32_t                                            BeamLevel                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         double                                             GaugePrecentage                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         void                                               ReturnValue
     */
    void UUI_SkillCustomHUD_BunnyActive4_C::UpdateBeamLevelGauge(int32_t BeamLevel, double GaugePrecentage)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Game/Widgets/SkillCustomHUD/UI_SkillCustomHUD_BunnyActive4.UI_SkillCustomHUD_BunnyActive4_C.UpdateBeamLevelGauge");
        
        UUI_SkillCustomHUD_BunnyActive4_C_UpdateBeamLevelGauge_Params params {};
        params.BeamLevel = BeamLevel;
        params.GaugePrecentage = GaugePrecentage;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Game/Widgets/SkillCustomHUD/UI_SkillCustomHUD_BunnyActive4.UI_SkillCustomHUD_BunnyActive4_C.ResetWidgetVisibilities
     *         Flags  -> (Public, BlueprintCallable, BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void UUI_SkillCustomHUD_BunnyActive4_C::ResetWidgetVisibilities()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Game/Widgets/SkillCustomHUD/UI_SkillCustomHUD_BunnyActive4.UI_SkillCustomHUD_BunnyActive4_C.ResetWidgetVisibilities");
        
        UUI_SkillCustomHUD_BunnyActive4_C_ResetWidgetVisibilities_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Game/Widgets/SkillCustomHUD/UI_SkillCustomHUD_BunnyActive4.UI_SkillCustomHUD_BunnyActive4_C.ShowWidget
     *         Flags  -> (Public, BlueprintCallable, BlueprintEvent)
     * Parameters:
     *         bool                                               bShow                                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         void                                               ReturnValue
     */
    void UUI_SkillCustomHUD_BunnyActive4_C::ShowWidget(bool bShow)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Game/Widgets/SkillCustomHUD/UI_SkillCustomHUD_BunnyActive4.UI_SkillCustomHUD_BunnyActive4_C.ShowWidget");
        
        UUI_SkillCustomHUD_BunnyActive4_C_ShowWidget_Params params {};
        params.bShow = bShow;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Game/Widgets/SkillCustomHUD/UI_SkillCustomHUD_BunnyActive4.UI_SkillCustomHUD_BunnyActive4_C.Construct
     *         Flags  -> (BlueprintCosmetic, Event, Public, BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void UUI_SkillCustomHUD_BunnyActive4_C::Construct()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Game/Widgets/SkillCustomHUD/UI_SkillCustomHUD_BunnyActive4.UI_SkillCustomHUD_BunnyActive4_C.Construct");
        
        UUI_SkillCustomHUD_BunnyActive4_C_Construct_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Game/Widgets/SkillCustomHUD/UI_SkillCustomHUD_BunnyActive4.UI_SkillCustomHUD_BunnyActive4_C.OnBeamLevelIncrease
     *         Flags  -> (BlueprintCallable, BlueprintEvent)
     * Parameters:
     *         int32_t                                            BeamLevel                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         double                                             ChargeTimeToNextLevel                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         bool                                               bMaxLevel                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         void                                               ReturnValue
     */
    void UUI_SkillCustomHUD_BunnyActive4_C::OnBeamLevelIncrease(int32_t BeamLevel, double ChargeTimeToNextLevel, bool bMaxLevel)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Game/Widgets/SkillCustomHUD/UI_SkillCustomHUD_BunnyActive4.UI_SkillCustomHUD_BunnyActive4_C.OnBeamLevelIncrease");
        
        UUI_SkillCustomHUD_BunnyActive4_C_OnBeamLevelIncrease_Params params {};
        params.BeamLevel = BeamLevel;
        params.ChargeTimeToNextLevel = ChargeTimeToNextLevel;
        params.bMaxLevel = bMaxLevel;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Game/Widgets/SkillCustomHUD/UI_SkillCustomHUD_BunnyActive4.UI_SkillCustomHUD_BunnyActive4_C.BP_OnSkillActivated
     *         Flags  -> (Event, Protected, BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void UUI_SkillCustomHUD_BunnyActive4_C::BP_OnSkillActivated()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Game/Widgets/SkillCustomHUD/UI_SkillCustomHUD_BunnyActive4.UI_SkillCustomHUD_BunnyActive4_C.BP_OnSkillActivated");
        
        UUI_SkillCustomHUD_BunnyActive4_C_BP_OnSkillActivated_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Game/Widgets/SkillCustomHUD/UI_SkillCustomHUD_BunnyActive4.UI_SkillCustomHUD_BunnyActive4_C.BP_OnSkillDeactivated
     *         Flags  -> (Event, Protected, BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void UUI_SkillCustomHUD_BunnyActive4_C::BP_OnSkillDeactivated()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Game/Widgets/SkillCustomHUD/UI_SkillCustomHUD_BunnyActive4.UI_SkillCustomHUD_BunnyActive4_C.BP_OnSkillDeactivated");
        
        UUI_SkillCustomHUD_BunnyActive4_C_BP_OnSkillDeactivated_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Game/Widgets/SkillCustomHUD/UI_SkillCustomHUD_BunnyActive4.UI_SkillCustomHUD_BunnyActive4_C.Destruct
     *         Flags  -> (BlueprintCosmetic, Event, Public, BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void UUI_SkillCustomHUD_BunnyActive4_C::Destruct()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Game/Widgets/SkillCustomHUD/UI_SkillCustomHUD_BunnyActive4.UI_SkillCustomHUD_BunnyActive4_C.Destruct");
        
        UUI_SkillCustomHUD_BunnyActive4_C_Destruct_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x03A3F420
     *         Name   -> Function /Game/UI/Game/Widgets/SkillCustomHUD/UI_SkillCustomHUD_BunnyActive4.UI_SkillCustomHUD_BunnyActive4_C.ExecuteUbergraph_UI_SkillCustomHUD_BunnyActive4
     *         Flags  -> (Final)
     * Parameters:
     *         int32_t                                            EntryPoint                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         void                                               ReturnValue
     */
    void UUI_SkillCustomHUD_BunnyActive4_C::ExecuteUbergraph_UI_SkillCustomHUD_BunnyActive4(int32_t EntryPoint)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UI/Game/Widgets/SkillCustomHUD/UI_SkillCustomHUD_BunnyActive4.UI_SkillCustomHUD_BunnyActive4_C.ExecuteUbergraph_UI_SkillCustomHUD_BunnyActive4");
        
        UUI_SkillCustomHUD_BunnyActive4_C_ExecuteUbergraph_UI_SkillCustomHUD_BunnyActive4_Params params {};
        params.EntryPoint = EntryPoint;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
