#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::ActorSequence
{
    // --------------------------------------------------
    // # Enums
    // --------------------------------------------------
    /**
     * Enum /Script/ActorSequence.EActorSequenceObjectReferenceType
     */
    enum class EActorSequenceObjectReferenceType : uint8_t
    {
        ContextActor  = 0,
        ExternalActor = 1,
        Component     = 2,
        MAX           = 3
    };

}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
