#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "AIModule_FEnvDirection.h"
#include "AIModule_ENUMS.h"
#include "AIModule_UEnvQueryTest.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::CoreUObject { class UClass; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::AIModule
{
    /**
     * Class /Script/AIModule.EnvQueryTest_Dot
     * Size -> 0x0048 (FullSize[0x0240] - InheritedSize[0x01F8])
     */
    class UEnvQueryTest_Dot : public AIModule::UEnvQueryTest
    {
    public:
        AIModule::FEnvDirection                                      LineA;                                                   //  Edit, DisableEditOnInstance, NoDestructor, Protected, NativeAccessSpecifierProtected
        AIModule::FEnvDirection                                      LineB;                                                   //  Edit, DisableEditOnInstance, NoDestructor, Protected, NativeAccessSpecifierProtected
        AIModule::EEnvTestDot                                        TestMode;                                                //  Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected
        bool                                                         bAbsoluteValue;                                          //  Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected
        uint8_t                                                      UnknownData_0000[0x6];                                   //  MISSED OFFSET (PADDING)

    public:
        static inline CoreUObject::UClass* StaticClass()
        {
            static CoreUObject::UClass* ptr = nullptr;
            if (!ptr)
                ptr = CoreUObject::UObject::FindClass("Class /Script/AIModule.EnvQueryTest_Dot");
            return ptr;
        }
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
