#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::CinematicCamera
{
    // --------------------------------------------------
    // # Enums
    // --------------------------------------------------
    /**
     * Enum /Script/CinematicCamera.ECameraFocusMethod
     */
    enum class ECameraFocusMethod : uint8_t
    {
        DoNotOverride = 0,
        Manual        = 1,
        Tracking      = 2,
        Disable       = 3,
        MAX           = 4
    };

}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
