#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "Engine_UMeshComponent.h"
#include "BasicTypes_TArray.h"
#include "CustomMeshComponent_FCustomMeshTriangle.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::CoreUObject { class UClass; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::CustomMeshComponent
{
    /**
     * Class /Script/CustomMeshComponent.CustomMeshComponent
     * Size -> 0x0010 (FullSize[0x04C0] - InheritedSize[0x04B0])
     */
    class UCustomMeshComponent : public Engine::UMeshComponent
    {
    public:
        uint8_t                                                      UnknownData_0000[0x10];                                  //  MISSED OFFSET (PADDING)

    public:
        bool SetCustomMeshTriangles(BasicTypes::TArray<CustomMeshComponent::FCustomMeshTriangle> Triangles);
        void ClearCustomMeshTriangles();
        void AddCustomMeshTriangles(BasicTypes::TArray<CustomMeshComponent::FCustomMeshTriangle> Triangles);
        static inline CoreUObject::UClass* StaticClass()
        {
            static CoreUObject::UClass* ptr = nullptr;
            if (!ptr)
                ptr = CoreUObject::UObject::FindClass("Class /Script/CustomMeshComponent.CustomMeshComponent");
            return ptr;
        }
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
