#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "Engine_FExpressionExecOutput.h"
#include "Engine_FExpressionInput.h"
#include "Engine_UMaterialExpression.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::CoreUObject { class UClass; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::Engine
{
    /**
     * Class /Script/Engine.MaterialExpressionIfThenElse
     * Size -> 0x0038 (FullSize[0x00E8] - InheritedSize[0x00B0])
     */
    class UMaterialExpressionIfThenElse : public Engine::UMaterialExpression
    {
    public:
        Engine::FExpressionExecOutput                                Then;                                                    //  NoDestructor, NativeAccessSpecifierPublic
        Engine::FExpressionExecOutput                                Else;                                                    //  NoDestructor, NativeAccessSpecifierPublic
        Engine::FExpressionInput                                     Condition;                                               //  NoDestructor, NativeAccessSpecifierPublic

    public:
        static inline CoreUObject::UClass* StaticClass()
        {
            static CoreUObject::UClass* ptr = nullptr;
            if (!ptr)
                ptr = CoreUObject::UObject::FindClass("Class /Script/Engine.MaterialExpressionIfThenElse");
            return ptr;
        }
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
