#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "Engine_FActorComponentTickFunction.h"
#include "BasicTypes_TArray.h"
#include "BasicTypes_FName.h"
#include "Engine_ENUMS.h"
#include "BasicTypes_UMulticastSparseDelegate.h"
#include "CoreUObject_UObject.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::Engine { class UAssetUserData; };
namespace CG::Engine { class UActorComponent; };
namespace CG::Engine { class AActor; };
namespace CG::CoreUObject { class UClass; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::Engine
{
    /**
     * Class /Script/Engine.ActorComponent
     * Size -> 0x0080 (FullSize[0x00A8] - InheritedSize[0x0028])
     */
    class UActorComponent : public CoreUObject::UObject
    {
    public:
        uint8_t                                                      UnknownData_0000[0x8];                                   //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        Engine::FActorComponentTickFunction                          PrimaryComponentTick;                                    //  Edit, DisableEditOnInstance, NativeAccessSpecifierPublic
        BasicTypes::TArray<BasicTypes::FName>                        ComponentTags;                                           //  Edit, BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic
        BasicTypes::TArray<Engine::UAssetUserData*>                  AssetUserData;                                           //  Edit, ExportObject, ZeroConstructor, ContainsInstancedReference, AdvancedDisplay, Protected, UObjectWrapper, NativeAccessSpecifierProtected
        uint8_t                                                      UnknownData_0001[0x4];                                   //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        int32_t                                                      UCSSerializationIndex;                                   //  ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate
        bool                                                         UnknownData_0002 : 3;                                    //  BIT_FIELD (PADDING)
        bool                                                         bNetAddressable : 1;                                     //  BIT_FIELD NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected
        bool                                                         bReplicateUsingRegisteredSubObjectList : 1;              //  BIT_FIELD Edit, BlueprintVisible, BlueprintReadOnly, Config, DisableEditOnInstance, NoDestructor, AdvancedDisplay, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected
        bool                                                         bReplicates : 1;                                         //  BIT_FIELD Edit, BlueprintVisible, BlueprintReadOnly, Net, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate
        bool                                                         UnknownData_0004 : 2;                                    //  BIT_FIELD (PADDING)
        uint8_t                                                      UnknownData_0003[0x1];                                   //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        bool                                                         bIsEditorOnly : 1;                                       //  BIT_FIELD Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        bool                                                         UnknownData_0007 : 1;                                    //  BIT_FIELD (PADDING)
        bool                                                         bCanEverAffectNavigation : 1;                            //  BIT_FIELD Edit, Config, NoDestructor, AdvancedDisplay, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected
        bool                                                         UnknownData_0006 : 1;                                    //  BIT_FIELD (PADDING)
        bool                                                         UnknownData_0005 : 1;                                    //  BIT_FIELD (PADDING)
        bool                                                         bIsActive : 1;                                           //  BIT_FIELD Net, Transient, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate
        bool                                                         bAutoActivate : 1;                                       //  BIT_FIELD Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        bool                                                         bEditableWhenInherited : 1;                              //  BIT_FIELD Edit, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        uint8_t                                                      UnknownData_0008[0x2];                                   //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        Engine::EComponentCreationMethod                             CreationMethod;                                          //  ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        BasicTypes::UMulticastSparseDelegate                         OnComponentActivated;                                    //  InstancedReference, BlueprintAssignable, NoDestructor, NativeAccessSpecifierPublic
        BasicTypes::UMulticastSparseDelegate                         OnComponentDeactivated;                                  //  InstancedReference, BlueprintAssignable, NoDestructor, NativeAccessSpecifierPublic
        uint8_t                                                      UnknownData_0009[0x10];                                  //  MISSED OFFSET (PADDING)

    public:
        void ToggleActive();
        void SetTickGroup(Engine::ETickingGroup NewTickGroup);
        void SetTickableWhenPaused(bool bTickableWhenPaused);
        void SetIsReplicated(bool ShouldReplicate);
        void SetComponentTickIntervalAndCooldown(float TickInterval);
        void SetComponentTickInterval(float TickInterval);
        void SetComponentTickEnabled(bool bEnabled);
        void SetAutoActivate(bool bNewAutoActivate);
        void SetActive(bool bNewActive, bool bReset);
        void RemoveTickPrerequisiteComponent(Engine::UActorComponent* PrerequisiteComponent);
        void RemoveTickPrerequisiteActor(Engine::AActor* PrerequisiteActor);
        void ReceiveTick(float DeltaSeconds);
        void ReceiveEndPlay(Engine::EEndPlayReason EndPlayReason);
        void ReceiveBeginPlay();
        void ReceiveAsyncPhysicsTick(float DeltaSeconds, float SimSeconds);
        void OnRep_IsActive();
        void K2_DestroyComponent(CoreUObject::UObject* Object);
        bool IsComponentTickEnabled();
        bool IsBeingDestroyed();
        bool IsActive();
        Engine::AActor* GetOwner();
        float GetComponentTickInterval();
        void Deactivate();
        bool ComponentHasTag(const BasicTypes::FName& Tag);
        void AddTickPrerequisiteComponent(Engine::UActorComponent* PrerequisiteComponent);
        void AddTickPrerequisiteActor(Engine::AActor* PrerequisiteActor);
        void Activate(bool bReset);
        static inline CoreUObject::UClass* StaticClass()
        {
            static CoreUObject::UClass* ptr = nullptr;
            if (!ptr)
                ptr = CoreUObject::UObject::FindClass("Class /Script/Engine.ActorComponent");
            return ptr;
        }
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
