#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "GameplayCameras_FCameraAnimationParams.h"
#include "GameplayCameras_FCameraAnimationHandle.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::TemplateSequence { class UCameraAnimationSequence; };
namespace CG::TemplateSequence { class UCameraAnimationSequencePlayer; };
namespace CG::TemplateSequence { class UCameraAnimationSequenceCameraStandIn; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::GameplayCameras
{
    /**
     * ScriptStruct /Script/GameplayCameras.ActiveCameraAnimationInfo
     * Size -> 0x0060
     */
    struct FActiveCameraAnimationInfo
    {
    public:
        TemplateSequence::UCameraAnimationSequence*                  Sequence;                                                //  ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic
        GameplayCameras::FCameraAnimationParams                      Params;                                                  //  NoDestructor, NativeAccessSpecifierPublic
        GameplayCameras::FCameraAnimationHandle                      Handle;                                                  //  NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        uint8_t                                                      UnknownData_0000[0x4];                                   //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        TemplateSequence::UCameraAnimationSequencePlayer*            Player;                                                  //  ZeroConstructor, Transient, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic
        TemplateSequence::UCameraAnimationSequenceCameraStandIn*     CameraStandIn;                                           //  ZeroConstructor, Transient, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic
        float                                                        EaseInCurrentTime;                                       //  ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        float                                                        EaseOutCurrentTime;                                      //  ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        bool                                                         bIsEasingIn;                                             //  ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        bool                                                         bIsEasingOut;                                            //  ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        uint8_t                                                      UnknownData_0001[0x6];                                   //  MISSED OFFSET (PADDING)
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
