#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "Engine_UActorComponent.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::GeometryCollectionEngine { class AGeometryCollectionDebugDrawActor; };
namespace CG::GeometryCollectionEngine { class AGeometryCollectionRenderLevelSetActor; };
namespace CG::CoreUObject { class UClass; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::GeometryCollectionEngine
{
    /**
     * Class /Script/GeometryCollectionEngine.GeometryCollectionDebugDrawComponent
     * Size -> 0x0018 (FullSize[0x00C0] - InheritedSize[0x00A8])
     */
    class UGeometryCollectionDebugDrawComponent : public Engine::UActorComponent
    {
    public:
        GeometryCollectionEngine::AGeometryCollectionDebugDrawActor* GeometryCollectionDebugDrawActor;                        //  ZeroConstructor, Deprecated, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic
        GeometryCollectionEngine::AGeometryCollectionRenderLevelSetActor* GeometryCollectionRenderLevelSetActor;                   //  Edit, ZeroConstructor, NoDestructor, AdvancedDisplay, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic
        uint8_t                                                      UnknownData_0000[0x8];                                   //  MISSED OFFSET (PADDING)

    public:
        static inline CoreUObject::UClass* StaticClass()
        {
            static CoreUObject::UClass* ptr = nullptr;
            if (!ptr)
                ptr = CoreUObject::UObject::FindClass("Class /Script/GeometryCollectionEngine.GeometryCollectionDebugDrawComponent");
            return ptr;
        }
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
