#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "BasicTypes_FName.h"
#include "Engine_FBoneReference.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::IKRig
{
    /**
     * ScriptStruct /Script/IKRig.BoneChain
     * Size -> 0x0030
     */
    struct FBoneChain
    {
    public:
        BasicTypes::FName                                            ChainName;                                               //  Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        Engine::FBoneReference                                       StartBone;                                               //  Edit, EditConst, NoDestructor, NativeAccessSpecifierPublic
        Engine::FBoneReference                                       EndBone;                                                 //  Edit, EditConst, NoDestructor, NativeAccessSpecifierPublic
        BasicTypes::FName                                            IKGoalName;                                              //  Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
