#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "BasicTypes_TArray.h"
#include "InteractiveToolsFramework_USelectionSet.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::CoreUObject { class UClass; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::InteractiveToolsFramework
{
    /**
     * Class /Script/InteractiveToolsFramework.MeshSelectionSet
     * Size -> 0x0040 (FullSize[0x0080] - InheritedSize[0x0040])
     */
    class UMeshSelectionSet : public InteractiveToolsFramework::USelectionSet
    {
    public:
        BasicTypes::TArray<int32_t>                                  Vertices;                                                //  ZeroConstructor, NativeAccessSpecifierPublic
        BasicTypes::TArray<int32_t>                                  Edges;                                                   //  ZeroConstructor, NativeAccessSpecifierPublic
        BasicTypes::TArray<int32_t>                                  Faces;                                                   //  ZeroConstructor, NativeAccessSpecifierPublic
        BasicTypes::TArray<int32_t>                                  Groups;                                                  //  ZeroConstructor, NativeAccessSpecifierPublic

    public:
        static inline CoreUObject::UClass* StaticClass()
        {
            static CoreUObject::UClass* ptr = nullptr;
            if (!ptr)
                ptr = CoreUObject::UObject::FindClass("Class /Script/InteractiveToolsFramework.MeshSelectionSet");
            return ptr;
        }
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
