#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "LiveLinkInterface_FLiveLinkSubjectKey.h"
#include "LiveLink_ENUMS.h"
#include "CoreUObject_FFrameRate.h"
#include "Engine_UTimecodeProvider.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::CoreUObject { class UClass; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::LiveLink
{
    /**
     * Class /Script/LiveLink.LiveLinkTimecodeProvider
     * Size -> 0x0090 (FullSize[0x00C0] - InheritedSize[0x0030])
     */
    class ULiveLinkTimecodeProvider : public Engine::UTimecodeProvider
    {
    public:
        LiveLinkInterface::FLiveLinkSubjectKey                       SubjectKey;                                              //  Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate
        LiveLink::ELiveLinkTimecodeProviderEvaluationType            Evaluation;                                              //  Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate
        bool                                                         bOverrideFrameRate;                                      //  Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate
        uint8_t                                                      UnknownData_0000[0x3];                                   //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        CoreUObject::FFrameRate                                      OverrideFrameRate;                                       //  Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate
        int32_t                                                      BufferSize;                                              //  Edit, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPrivate
        uint8_t                                                      UnknownData_0001[0x64];                                  //  MISSED OFFSET (PADDING)

    public:
        static inline CoreUObject::UClass* StaticClass()
        {
            static CoreUObject::UClass* ptr = nullptr;
            if (!ptr)
                ptr = CoreUObject::UObject::FindClass("Class /Script/LiveLink.LiveLinkTimecodeProvider");
            return ptr;
        }
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
