#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "M1Data_FM1TemplateId.h"
#include "Engine_AActor.h"
#include "M1_FM1MiniGameResult.h"
#include "M1_ENUMS.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::M1 { class UM1ContributionComponent; };
namespace CG::M1 { class UM1FieldObjectActivateBehavior; };
namespace CG::Engine { class AController; };
namespace CG::CoreUObject { class UClass; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::M1
{
    /**
     * Class /Script/M1.M1MiniGameActor
     * Size -> 0x0030 (FullSize[0x0278] - InheritedSize[0x0248])
     */
    class AM1MiniGameActor : public Engine::AActor
    {
    public:
        M1Data::FM1TemplateId                                        MiniGameTid;                                             //  Net, Transient, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate
        M1Data::FM1TemplateId                                        FieldDifficultyTid;                                      //  Net, Transient, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate
        uint8_t                                                      UnknownData_0000[0x18];                                  //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        M1::UM1ContributionComponent*                                ContributionComponent;                                   //  ExportObject, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate
        M1::UM1FieldObjectActivateBehavior*                          ActivateBehavior;                                        //  ZeroConstructor, Transient, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate

    public:
        void ServerOnMiniGameEnded(const M1::FM1MiniGameResult& InResult);
        void ServerDropItems(Engine::AController* InInstigator);
        void ClientStopMiniGame();
        void ClientStartMiniGame(const M1Data::FM1TemplateId& InMiniGameTid, const M1Data::FM1TemplateId& InPlayerTid, const M1Data::FM1TemplateId& InFieldDifficultyTid, M1::EM1MiniGameDifficulty InDifficulty);
        static inline CoreUObject::UClass* StaticClass()
        {
            static CoreUObject::UClass* ptr = nullptr;
            if (!ptr)
                ptr = CoreUObject::UObject::FindClass("Class /Script/M1.M1MiniGameActor");
            return ptr;
        }
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
