#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "BasicTypes_TWeakObjectPtr.h"
#include "M1_UM1UIData.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::M1 { class UM1RuneSockets; };
namespace CG::CoreUObject { class UClass; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::M1
{
    /**
     * Class /Script/M1.M1UIDataRuneBoardCapacityInfo
     * Size -> 0x0008 (FullSize[0x0040] - InheritedSize[0x0038])
     */
    class UM1UIDataRuneBoardCapacityInfo : public M1::UM1UIData
    {
    public:
        BasicTypes::TWeakObjectPtr<M1::UM1RuneSockets>               RuneSockets;                                             //  ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected

    public:
        int32_t GetProficiencyLevel();
        int32_t GetMaxCapacity();
        int32_t GetMasteryRank();
        int64_t GetCostOfAttachedRunes();
        int32_t GetCharacterLevel();
        int32_t GetCapacityIncreaseItemUseLimit();
        int32_t GetCapacityIncreaseItemUseCount();
        int32_t GetCapacityIncreaseAmount();
        static inline CoreUObject::UClass* StaticClass()
        {
            static CoreUObject::UClass* ptr = nullptr;
            if (!ptr)
                ptr = CoreUObject::UObject::FindClass("Class /Script/M1.M1UIDataRuneBoardCapacityInfo");
            return ptr;
        }
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
