#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "M1_FM1SocialMotionFlowSetting.h"
#include "BasicTypes_TArray.h"
#include "BasicTypes_TWeakObjectPtr.h"
#include "CoreUObject_FTransform.h"
#include "M1_UM1SocialMotion.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::M1 { class UM1GroupSocialMotion; };
namespace CG::M1 { class AM1SocialMotionMimicMesh; };
namespace CG::CoreUObject { class UClass; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::M1
{
    /**
     * Class /Script/M1.M1FollowSocialMotion
     * Size -> 0x0070 (FullSize[0x03F0] - InheritedSize[0x0380])
     */
    class UM1FollowSocialMotion : public M1::UM1SocialMotion
    {
    public:
        bool                                                         bSyncWithLeader;                                         //  Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate
        uint8_t                                                      UnknownData_0000[0x3];                                   //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        M1::FM1SocialMotionFlowSetting                               FlowSettingWhenOccupiedFully;                            //  Edit, DisableEditOnInstance, NoDestructor, NativeAccessSpecifierPrivate
        BasicTypes::TArray<M1::FM1SocialMotionFlowSetting>           FlowSettingWhileWaiting;                                 //  Edit, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPrivate
        BasicTypes::TWeakObjectPtr<M1::UM1GroupSocialMotion>         SocialMotionLeader;                                      //  ZeroConstructor, Transient, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate
        CoreUObject::FTransform                                      SocialMotionTransform;                                   //  Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate
        BasicTypes::TWeakObjectPtr<M1::AM1SocialMotionMimicMesh>     MimicMesh;                                               //  ZeroConstructor, Transient, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate
        uint8_t                                                      UnknownData_0001[0x8];                                   //  MISSED OFFSET (PADDING)

    public:
        static inline CoreUObject::UClass* StaticClass()
        {
            static CoreUObject::UClass* ptr = nullptr;
            if (!ptr)
                ptr = CoreUObject::UObject::FindClass("Class /Script/M1.M1FollowSocialMotion");
            return ptr;
        }
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
