#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "AIModule_UAIPerceptionComponent.h"
#include "AIModule_FActorPerceptionUpdateInfo.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::Engine { class AActor; };
namespace CG::CoreUObject { class UClass; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::M1
{
    /**
     * Class /Script/M1.M1AIPerceptionComponent
     * Size -> 0x0068 (FullSize[0x0200] - InheritedSize[0x0198])
     */
    class UM1AIPerceptionComponent : public AIModule::UAIPerceptionComponent
    {
    public:
        uint8_t                                                      UnknownData_0000[0x68];                                  //  MISSED OFFSET (PADDING)

    public:
        void OnPerceptionUpdateInfo(const AIModule::FActorPerceptionUpdateInfo& InUpdatedInfo);
        void OnPeceptionActorForgotten(Engine::AActor* InForgottenActor);
        static inline CoreUObject::UClass* StaticClass()
        {
            static CoreUObject::UClass* ptr = nullptr;
            if (!ptr)
                ptr = CoreUObject::UObject::FindClass("Class /Script/M1.M1AIPerceptionComponent");
            return ptr;
        }
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
