#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "M1_FM1ChattingSetting.h"
#include "BasicTypes_TMap.h"
#include "M1_ENUMS.h"
#include "CoreUObject_FLinearColor.h"
#include "M1Data_ENUMS.h"
#include "DeveloperSettings_UDeveloperSettings.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::CoreUObject { class UClass; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::M1
{
    /**
     * Class /Script/M1.M1UIDeveloperSettings
     * Size -> 0x0118 (FullSize[0x0150] - InheritedSize[0x0038])
     */
    class UM1UIDeveloperSettings : public DeveloperSettings::UDeveloperSettings
    {
    public:
        M1::FM1ChattingSetting                                       ChattingSetting;                                         //  Edit, Config, DisableEditOnInstance, NoDestructor, NativeAccessSpecifierPublic
        float                                                        MaxDistanceAimedAtMonster;                               //  Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        float                                                        MaxDistanceCrosshairDistUI;                              //  Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        float                                                        DamageTrackingDuration;                                  //  Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        int32_t                                                      DamageTrackingMaxCount;                                  //  Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        float                                                        DeathWarningRate;                                        //  Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        uint8_t                                                      UnknownData_0000[0x4];                                   //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        BasicTypes::TMap<M1::EM1RuneInfoTextColorType, CoreUObject::FLinearColor> RuneInfoTextColorMap;                                    //  Edit, Config, DisableEditOnInstance, NativeAccessSpecifierPublic
        BasicTypes::TMap<M1Data::EM1RoundsType, CoreUObject::FLinearColor> RoundsColors;                                            //  Edit, Config, DisableEditOnInstance, NativeAccessSpecifierPublic

    public:
        static inline CoreUObject::UClass* StaticClass()
        {
            static CoreUObject::UClass* ptr = nullptr;
            if (!ptr)
                ptr = CoreUObject::UObject::FindClass("Class /Script/M1.M1UIDeveloperSettings");
            return ptr;
        }
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
