#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "M1Data_FM1CommonShopData.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::M1Data
{
    /**
     * ScriptStruct /Script/M1Data.M1BattlePassShopData
     * Size -> 0x0000 (FullSize[0x0060] - InheritedSize[0x0060])
     */
    struct FM1BattlePassShopData : public M1Data::FM1CommonShopData
    {
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
