#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "M1Data_FM1RewardType.h"
#include "BasicTypes_TArray.h"
#include "M1Data_FM1InstanceDungeonScoreSection.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::M1Data
{
    /**
     * ScriptStruct /Script/M1Data.M1InstanceDungeonReward
     * Size -> 0x0050
     */
    struct FM1InstanceDungeonReward
    {
    public:
        M1Data::FM1RewardType                                        Item;                                                    //  Edit, NativeAccessSpecifierPublic
        BasicTypes::TArray<M1Data::FM1InstanceDungeonScoreSection>   ScoreSection;                                            //  Edit, ZeroConstructor, NativeAccessSpecifierPublic
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
