#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "MetasoundFrontend_FMetasoundFrontendClassName.h"
#include "MetasoundFrontend_FMetasoundFrontendVersionNumber.h"
#include "MetasoundFrontend_ENUMS.h"
#include "CoreUObject_FGuid.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::MetasoundFrontend
{
    /**
     * ScriptStruct /Script/MetasoundFrontend.MetasoundFrontendClassMetadata
     * Size -> 0x0034
     */
    struct FMetasoundFrontendClassMetadata
    {
    public:
        MetasoundFrontend::FMetasoundFrontendClassName               ClassName;                                               //  Edit, EditConst, NoDestructor, NativeAccessSpecifierPrivate
        MetasoundFrontend::FMetasoundFrontendVersionNumber           Version;                                                 //  Edit, EditConst, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate
        MetasoundFrontend::EMetasoundFrontendClassType               Type;                                                    //  Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate
        bool                                                         bIsDeprecated;                                           //  Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate
        bool                                                         bAutoUpdateManagesInterface;                             //  ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate
        uint8_t                                                      UnknownData_0000[0x1];                                   //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        CoreUObject::FGuid                                           ChangeID;                                                //  ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
