#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "BasicTypes_TArray.h"
#include "BasicTypes_FString.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::Niagara
{
    /**
     * ScriptStruct /Script/Niagara.NiagaraSimpleClientInfo
     * Size -> 0x0040
     */
    struct FNiagaraSimpleClientInfo
    {
    public:
        BasicTypes::TArray<BasicTypes::FString>                      Systems;                                                 //  Edit, ZeroConstructor, NativeAccessSpecifierPublic
        BasicTypes::TArray<BasicTypes::FString>                      Actors;                                                  //  Edit, ZeroConstructor, NativeAccessSpecifierPublic
        BasicTypes::TArray<BasicTypes::FString>                      Components;                                              //  Edit, ZeroConstructor, NativeAccessSpecifierPublic
        BasicTypes::TArray<BasicTypes::FString>                      Emitters;                                                //  Edit, ZeroConstructor, NativeAccessSpecifierPublic
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
