#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "BasicTypes_TArray.h"
#include "Niagara_FNiagaraVariable.h"
#include "Niagara_FNiagaraVariableLayoutInfo.h"
#include "Niagara_FNiagaraDataSetID.h"
#include "Niagara_ENUMS.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::Niagara
{
    /**
     * ScriptStruct /Script/Niagara.NiagaraDataSetCompiledData
     * Size -> 0x0048
     */
    struct FNiagaraDataSetCompiledData
    {
    public:
        BasicTypes::TArray<Niagara::FNiagaraVariable>                Variables;                                               //  ZeroConstructor, NativeAccessSpecifierPublic
        BasicTypes::TArray<Niagara::FNiagaraVariableLayoutInfo>      VariableLayouts;                                         //  ZeroConstructor, NativeAccessSpecifierPublic
        Niagara::FNiagaraDataSetID                                   ID;                                                      //  NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        int32_t                                                      TotalFloatComponents;                                    //  ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        int32_t                                                      TotalInt32Components;                                    //  ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        int32_t                                                      TotalHalfComponents;                                     //  ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        bool                                                         bRequiresPersistentIDs : 1;                              //  BIT_FIELD NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        uint8_t                                                      UnknownData_0000[0x3];                                   //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        Niagara::ENiagaraSimTarget                                   SimTarget;                                               //  ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        uint8_t                                                      UnknownData_0001[0xB];                                   //  MISSED OFFSET (PADDING)
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
