#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "Engine_FPointerToUberGraphFrame.h"
#include "BasicTypes_FString.h"
#include "M1_UM1UIWidget.h"
#include "BasicTypes_FText.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::UMG { class UWidgetAnimation; };
namespace CG::M1 { class UM1TextBlock; };
namespace CG::CoreUObject { class UClass; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::UI_Deco_Back_Title
{
    /**
     * WidgetBlueprintGeneratedClass /Game/UI/Components/UI_Deco_Back_Title.UI_Deco_Back_Title_C
     * Size -> 0x0028 (FullSize[0x0730] - InheritedSize[0x0708])
     */
    class UUI_Deco_Back_Title_C : public M1::UM1UIWidget
    {
    public:
        Engine::FPointerToUberGraphFrame                             UberGraphFrame;                                          //  ZeroConstructor, Transient, DuplicateTransient
        UMG::UWidgetAnimation*                                       UIAnim_Open;                                             //  BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash
        M1::UM1TextBlock*                                            TB_Title;                                                //  BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash
        BasicTypes::FString                                          LabelUIKey;                                              //  Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash

    public:
        void SetUIString(const BasicTypes::FText& Text);
        void PreConstruct(bool IsDesignTime);
        void Construct();
        void ExecuteUbergraph_UI_Deco_Back_Title(int32_t EntryPoint);
        static inline CoreUObject::UClass* StaticClass()
        {
            static CoreUObject::UClass* ptr = nullptr;
            if (!ptr)
                ptr = CoreUObject::UObject::FindClass("WidgetBlueprintGeneratedClass /Game/UI/Components/UI_Deco_Back_Title.UI_Deco_Back_Title_C");
            return ptr;
        }
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
