#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "M1_UM1UIGameCenter_PerkCustom.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::CoreUObject { class UClass; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::UI_GameCenter_PerkCustom
{
    /**
     * WidgetBlueprintGeneratedClass /Game/UI/Game/Widgets/UI_GameCenter_PerkCustom.UI_GameCenter_PerkCustom_C
     * Size -> 0x0000 (FullSize[0x0760] - InheritedSize[0x0760])
     */
    class UUI_GameCenter_PerkCustom_C : public M1::UM1UIGameCenter_PerkCustom
    {
    public:
        static inline CoreUObject::UClass* StaticClass()
        {
            static CoreUObject::UClass* ptr = nullptr;
            if (!ptr)
                ptr = CoreUObject::UObject::FindClass("WidgetBlueprintGeneratedClass /Game/UI/Game/Widgets/UI_GameCenter_PerkCustom.UI_GameCenter_PerkCustom_C");
            return ptr;
        }
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
