#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "Engine_FPointerToUberGraphFrame.h"
#include "M1_UM1UIMetaGameGuidePanel.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::UMG { class UImage; };
namespace CG::UI_SquareHighlight { class UUI_SquareHighlight_C; };
namespace CG::CoreUObject { class UClass; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::UI_GuidePanel
{
    /**
     * WidgetBlueprintGeneratedClass /Game/UI/Common/UI_GuidePanel.UI_GuidePanel_C
     * Size -> 0x0018 (FullSize[0x0768] - InheritedSize[0x0750])
     */
    class UUI_GuidePanel_C : public M1::UM1UIMetaGameGuidePanel
    {
    public:
        Engine::FPointerToUberGraphFrame                             UberGraphFrame;                                          //  ZeroConstructor, Transient, DuplicateTransient
        UMG::UImage*                                                 B_Center;                                                //  BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash
        UI_SquareHighlight::UUI_SquareHighlight_C*                   UI_SquareHighlight;                                      //  BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash

    public:
        void Construct();
        void BP_ShowDimmedBackground(bool InVisible);
        void BP_ShowHightlightFrame(bool InVisible);
        void ExecuteUbergraph_UI_GuidePanel(int32_t EntryPoint);
        static inline CoreUObject::UClass* StaticClass()
        {
            static CoreUObject::UClass* ptr = nullptr;
            if (!ptr)
                ptr = CoreUObject::UObject::FindClass("WidgetBlueprintGeneratedClass /Game/UI/Common/UI_GuidePanel.UI_GuidePanel_C");
            return ptr;
        }
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
