#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "BasicTypes_TArray.h"
#include "VariantManagerContent_FVariantDependency.h"
#include "BasicTypes_FText.h"
#include "CoreUObject_UObject.h"
#include "BasicTypes_FString.h"
#include "CoreUObject_FTransform.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::VariantManagerContent { class UVariantObjectBinding; };
namespace CG::Engine { class UTexture2D; };
namespace CG::VariantManagerContent { class UVariantSet; };
namespace CG::VariantManagerContent { class ULevelVariantSets; };
namespace CG::VariantManagerContent { class UVariant; };
namespace CG::Engine { class AActor; };
namespace CG::CoreUObject { class UClass; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::VariantManagerContent
{
    /**
     * Class /Script/VariantManagerContent.Variant
     * Size -> 0x0058 (FullSize[0x0080] - InheritedSize[0x0028])
     */
    class UVariant : public CoreUObject::UObject
    {
    public:
        BasicTypes::TArray<VariantManagerContent::FVariantDependency> Dependencies;                                            //  ZeroConstructor, NativeAccessSpecifierPrivate
        BasicTypes::FText                                            DisplayText;                                             //  Deprecated, NativeAccessSpecifierPrivate
        uint8_t                                                      UnknownData_0000[0x18];                                  //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        BasicTypes::TArray<VariantManagerContent::UVariantObjectBinding*> ObjectBindings;                                          //  ExportObject, ZeroConstructor, ContainsInstancedReference, UObjectWrapper, NativeAccessSpecifierPrivate
        Engine::UTexture2D*                                          Thumbnail;                                               //  ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate

    public:
        void SwitchOn();
        void SetThumbnailFromTexture(Engine::UTexture2D* NewThumbnail);
        void SetThumbnailFromFile(const BasicTypes::FString& FilePath);
        void SetThumbnailFromEditorViewport();
        void SetThumbnailFromCamera(CoreUObject::UObject* WorldContextObject, const CoreUObject::FTransform& CameraTransform, float FOVDegrees, float MinZ, float Gamma);
        void SetDisplayText(const BasicTypes::FText& NewDisplayText);
        void SetDependency(int32_t Index, VariantManagerContent::FVariantDependency* Dependency);
        bool IsActive();
        Engine::UTexture2D* GetThumbnail();
        VariantManagerContent::UVariantSet* GetParent();
        int32_t GetNumDependencies();
        int32_t GetNumActors();
        BasicTypes::FText GetDisplayText();
        BasicTypes::TArray<VariantManagerContent::UVariant*> GetDependents(VariantManagerContent::ULevelVariantSets* LevelVariantSets, bool bOnlyEnabledDependencies);
        VariantManagerContent::FVariantDependency GetDependency(int32_t Index);
        Engine::AActor* GetActor(int32_t ActorIndex);
        void DeleteDependency(int32_t Index);
        int32_t AddDependency(VariantManagerContent::FVariantDependency* Dependency);
        static inline CoreUObject::UClass* StaticClass()
        {
            static CoreUObject::UClass* ptr = nullptr;
            if (!ptr)
                ptr = CoreUObject::UObject::FindClass("Class /Script/VariantManagerContent.Variant");
            return ptr;
        }
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
