#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    TFDCG                       |
 * | Version: 1                           |
 * | Date:    08/22/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "BasicTypes_FName.h"
#include "Engine_FInputScaleBiasClampConstants.h"
#include "Engine_ENUMS.h"
#include "Engine_FAnimNodeFunctionRef.h"
#include "Engine_FAnimSubsystem_PropertyAccess.h"
#include "Engine_FAnimSubsystem_Base.h"
#include "Engine_FAnimBlueprintConstantData.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::WC_AnimBP
{
    /**
     * ScriptStruct /Game/Characters/Weapon/WireCaster/WC_AnimBP.WC_AnimBP_C.AnimBlueprintGeneratedConstantData
     * Size -> 0x0137 (FullSize[0x0138] - InheritedSize[0x0001])
     */
    struct FAnimBlueprintGeneratedConstantData : public Engine::FAnimBlueprintConstantData
    {
    public:
        uint8_t                                                      UnknownData_0000[0x3];                                   //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        BasicTypes::FName                                            __NameProperty_79;                                       //  BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        BasicTypes::FName                                            __NameProperty_80;                                       //  BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        int32_t                                                      __IntProperty_81;                                        //  BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        BasicTypes::FName                                            __NameProperty_82;                                       //  BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        int32_t                                                      __IntProperty_83;                                        //  BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        BasicTypes::FName                                            __NameProperty_84;                                       //  BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        int32_t                                                      __IntProperty_85;                                        //  BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        float                                                        __FloatProperty_86;                                      //  BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        Engine::FInputScaleBiasClampConstants                        __StructProperty_87;                                     //  BlueprintVisible, NoDestructor
        float                                                        __FloatProperty_88;                                      //  BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        bool                                                         __BoolProperty_89;                                       //  BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        Engine::EAnimSyncMethod                                      __EnumProperty_90;                                       //  BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        Engine::EAnimGroupRole                                       __ByteProperty_91;                                       //  BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        uint8_t                                                      UnknownData_0001[0x1];                                   //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        BasicTypes::FName                                            __NameProperty_92;                                       //  BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        BasicTypes::FName                                            __NameProperty_93;                                       //  BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        int32_t                                                      __IntProperty_94;                                        //  BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        uint8_t                                                      UnknownData_0002[0x4];                                   //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        Engine::FAnimNodeFunctionRef                                 __StructProperty_95;                                     //  BlueprintVisible, NoDestructor
        Engine::FAnimSubsystem_PropertyAccess                        AnimBlueprintExtension_PropertyAccess;
        Engine::FAnimSubsystem_Base                                  AnimBlueprintExtension_Base;
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
